### ISSUE TITLE
Did not return a View from onCreateView() or this was called before onCreateView()

### ISSUE THREAD

**Issue by DmitriyGl** [wada811/DataBinding-ktx#12]
Hello, Dear developers of this library. Thank you for your work. I believe that you can help me with some problem.

For a large amount of time, I periodically receive crash reports. There are not very many devices on which this happens, but this is inconvement. This devices are quite diverse, but there are both new and old models.

I get the following error in the report:

`Fatal Exception: java.lang.IllegalStateException: Fragment MyFragment did not return a View from onCreateView() or this was called before onCreateView().`
      `at androidx.fragment.app.Fragment.requireView(Fragment.java:1962)`
      `at com.wada811.databinding.FragmentDataBinding$dataBinding$1.getValue(FragmentDataBinding.kt:16)`
      `at com.wada811.databinding.FragmentDataBinding$dataBinding$1.getValue(FragmentDataBinding.kt:13)`

I followed all the recommendations for working with the library, but the error persists. 

Please help me solve this problem, I really need your advice. Thank you!

**Comment by wada811** [comment]
Thank you for using this library.
This error message is cofusing.
Probably, you use `binding` variable after `onDestroyView()`.
Please confirm it.

**Comment by DmitriyGl** [comment]
Thanks for the answer. But no, I dont use `binding` variable after `onDestroyView()`. In that case, I would always have a error, but no.

**Comment by wada811** [comment]
Ok, please give me sample code.

**Comment by DmitriyGl** [comment]
Based on data from FireBase Crashlytics I found that problem in FragmentDataBinding (package com.wada811.databinding) string 16.  

`(requireView().getTag(property.name.hashCode()) as? T)?.let { return it }`

You use requireView, but in some situations, where View have not found, it can throw IllegalStateException. I think that if you don't use requireView() on this place, problem will gone. Can you check it please?

**Comment by wada811** [comment]
If I don't use requireView(), I use `bind<T>(requireView())` in line 17 for returning ViewDataBinding as not null.
cf. https://github.com/wada811/DataBinding-ktx/blob/master/DataBinding-ktx/src/main/java/com/wada811/databinding/FragmentDataBinding.kt#L17

This problem is not requireView(). Is the real problem in your Fragment's onCreateView(), isn't it?
Do you return consistently View as not null in Fragment's onCreateView()?

**Comment by DmitriyGl** [comment]
Thanks for the answer. Unfortunately I don't use onCreateView, because I use Fragments secondary constructor passing layout res id. You have an example in the documentation, I do exactly the same. https://github.com/wada811/DataBinding-ktx#fragment

**Comment by wada811** [comment]
Umm...
Do you use the binding variable before onCreateView?

**Comment by wada811** [comment]
@DmitriyGl 
You may be using the binding property after onDestroyView in your listener or callback.

Please use `withBinding` method that released in 6.0.0.

Thank you.
