### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by houssemzaier** [wada811/DataBinding-ktx#13]
Thank you for sharing that work !
In the `ActivityDataBinding.kt` which is using the lazy delegate. 
You made an `object` implementing the `lazy `interface and storing the value in the `binding `reference.
-> line 12 `private var binding: T? = null`. (this var is **static** 💀 )
This is so bad and even as this causes a memory leak that will never free the attached activity to that reference.
You should make a simple class not a singleton.
I can do a pull request to fix that if you think that this could help you.
Just let me know 👍

**Comment by wada811** [comment]
@houssemzaier 
Thank you for your report.
Please make a pull request.
