### ISSUE TITLE
DataBinding overrides ViewStub implementation

### ISSUE THREAD

**Issue by beigirad** [wada811/DataBinding-ktx#9]
DataBinding and ViewBinding has different behavior and implementation in the usage of `ViewStub`. ViewBinding has normal implementation but DataBinding uses something named `ViewStubProxy` with different APIs.

When I just enabled ViewBinding in my application and then added `databinding-ktx` dependency, the normal behavior of ViewStub overrided by DataBinding API.

To fix this issue I had to copy/paste this repository source code in my project.

I have a request to separate `viewbinding` and `databinding` artifacts.

**Comment by wada811** [comment]
Thank you for your reporting. I just understand `ViewStubProxy`. Sure, the following is troublesome.

https://github.com/wada811/DataBinding-ktx/blob/d5b0d847e5d739988d7c375c46860ebbda6e3c6e/sample/src/main/java/com/wada811/databindingktx/viewbinding/ViewBindingFragment.kt#L15-L21

[ViewBinding-ktx/sample/src/main/java/com/wada811/viewbindingktx/ViewBindingFragment.kt](https://github.com/wada811/ViewBinding-ktx/blob/49d28ea0e6829ea012fd269f77cf3c9c52bcd3e5/sample/src/main/java/com/wada811/viewbindingktx/ViewBindingFragment.kt#L14-L18)
![image](https://user-images.githubusercontent.com/1378923/87945456-b6b22c00-cadb-11ea-89c4-7ab41a5c627a.png)

So, I had created [ViewBinding-ktx](https://github.com/wada811/ViewBinding-ktx) and released [DataBinding-ktx 5.0.0](https://github.com/wada811/DataBinding-ktx/releases/tag/5.0.0).
Please try it.
